#!/bin/sh
#
# chkconfig: 345 61 11
# description: Startup script for the Arkeia Network Backup WUI daemon
#
### BEGIN INIT INFO
# Provides:          arkwui
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     S 2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The Arkeia Network Backup WUI daemon
### END INIT INFO
#
##############################################################################

# FIXME status is not implemented
# FIXME exit statuses are prolly not right

set_httpd_conf()
{
	# Determine the group of the user 'nobody' and update httpd.conf with
	# it.
	nobodygroup=`id nobody -ng`
	if [ "$nobodygroup" != "nogroup" ] ; then
		nobodygroup="nobody"
	fi
	sed -i -e "s/@HTTPD_GROUP/$nobodygroup/" /opt/arkeia/wui/httpd/conf/httpd.conf
}

USAGE="Usage: $0 {force-reload | restart | start | stop}"

HTTPD_BIN="/opt/arkeia/wui/httpd"/bin/apachectl
action="$1"
echo "$0: $action the Arkeia Web User Interface server"
case "$action" in
start|stop)
	if test ! -x "$HTTPD_BIN"
	then
		echo "$HTTPD_BIN does not exist or is not executable" 1>&2
		exit 1
	else
		set_httpd_conf
		"$HTTPD_BIN" -k "$action"
	fi
	;;
restart|force-reload)
	if test ! -x "$HTTPD_BIN"
	then
		echo "$HTTPD_BIN does not exist or is not executable" 1>&2
		exit 1
	else
		set_httpd_conf
		"$HTTPD_BIN" -k stop
		"$HTTPD_BIN" -k start
	fi
	;;
*)
	echo "$USAGE"
	;;
esac
exit 0
